package siit

import (
	"slices"

	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
)

/**
 * RFC 7915 Sections 4.4 and 5.4 (ICMP errors generated by the translator)
 */

func (t *Translator) generateIPv6ParameterProblem(ip *layers.IPv6, pointer uint32) TranslatedPacket {
	outer := &layers.IPv6{
		Version:    6,
		NextHeader: layers.IPProtocolICMPv6,
		HopLimit:   64,
		SrcIP:      t.mapIPv4ToIPv6(t.ipv4RouterAddress),
		DstIP:      ip.SrcIP,
	}

	// RFC 4443 Section 3.4: as much of the invoking packet as fits is quoted.
	invoking := slices.Concat(ip.Contents, ip.Payload)
	if ip.HopByHop != nil {
		// gopacket decodes a leading Hop-by-Hop header out of the payload, so put it back.
		invoking = slices.Concat(ip.Contents, ip.HopByHop.Contents, ip.Payload)
	}
	message := newICMPv6(outer, 4, 0, pointer, invoking[:min(len(invoking), ipv6ICMPErrorPayloadMaximum)])
	return serializeTranslatedPacket(completeOptions, outer.SrcIP, outer.DstIP, outer, gopacket.Payload(message))
}

func (t *Translator) generateIPv6TimeExceeded(ip *layers.IPv4) TranslatedPacket {
	// Nothing can be quoted for the packets that must not trigger an error (ICMP errors).
	quote := t.translateQuotedIPv4(slices.Concat(ip.Contents, ip.Payload))
	if quote == nil {
		return TranslatedPacket{}
	}

	outer := &layers.IPv6{
		Version: 6, NextHeader: layers.IPProtocolICMPv6, HopLimit: 64,
		SrcIP: t.mapIPv4ToIPv6(t.ipv4RouterAddress), DstIP: t.mapIPv4ToIPv6(ip.SrcIP),
	}

	message := newICMPv6(outer, 3, 0, 0, quote[:min(len(quote), ipv6ICMPErrorPayloadMaximum)])
	return serializeTranslatedPacket(completeOptions, outer.SrcIP, outer.DstIP, outer, gopacket.Payload(message))
}

func (t *Translator) generateIPv4TimeExceeded(ip *layers.IPv6) TranslatedPacket {
	if !t.hasIPv6ToIPv4Mapping(ip.SrcIP) || t.isForbiddenIPv6(ip.SrcIP) {
		return TranslatedPacket{SrcIP: t.ipv4RouterAddress}
	}

	quote := t.translateQuotedIPv6(slices.Concat(ip.Contents, ip.Payload))
	if quote == nil {
		return TranslatedPacket{SrcIP: t.ipv4RouterAddress}
	}

	outer := &layers.IPv4{
		Version: 4, IHL: 5, Protocol: layers.IPProtocolICMPv4, TTL: 64,
		SrcIP: t.ipv4RouterAddress, DstIP: t.mapIPv6ToIPv4(ip.SrcIP),
	}

	message := newICMPv4(11, 0, 0, quote[:min(len(quote), ipv4ICMPErrorPayloadMaximum)])
	return serializeTranslatedPacket(completeOptions, outer.SrcIP, outer.DstIP, outer, gopacket.Payload(message))
}

func (t *Translator) generateIPv4SourceRouteFailed(ip *layers.IPv4) TranslatedPacket {
	outer := &layers.IPv4{
		Version: 4, IHL: 5, Protocol: layers.IPProtocolICMPv4, TTL: 64,
		SrcIP: t.ipv4RouterAddress, DstIP: ip.SrcIP,
	}

	quote := slices.Concat(ip.Contents, ip.Payload[:min(len(ip.Payload), icmpErrorQuoteLength)])
	message := newICMPv4(3, 5, 0, quote)
	return serializeTranslatedPacket(completeOptions, outer.SrcIP, outer.DstIP, outer, gopacket.Payload(message))
}
